name: WakaTime stat

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "1 4,8,12,16 * * *" # runs at every 4h, 北京时间 12:01-00:01

jobs:

  wakatime:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: fakeYanss/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # following flags are required, only if this is not on
          # profile readme, remove the leading `#` to use them
          #GH_TOKEN: ${{ secrets.GH_TOKEN }}
          #REPOSITORY: <gh_username/gh_username>
          LANG_COUNT: 5
          BLOCKS: ->
